FROM python:2-stretch

RUN mkdir /get5
WORKDIR /get5
RUN wget "https://github.com/PhlexPlexico/get5-web/archive/1.0.zip"
RUN unzip 1.0.zip
WORKDIR get5-web-1.0
RUN pip install -r requirements.txt
ADD entry.sh entry.sh
RUN chmod a+rx entry.sh
ADD prod_config.py instance/prod_config.py

CMD ./entry.sh
