FROM python:2-stretch

RUN git clone https://github.com/splewis/get5-web /get5
WORKDIR /get5
RUN pip install -r requirements.txt
ADD entry.sh entry.sh
RUN chmod a+rx entry.sh
ADD prod_config.py instance/prod_config.py

CMD ./entry.sh
