FROM python:2-stretch

RUN mkdir /get5
WORKDIR /get5
RUN wget "https://github.com/jenrik/get5-web/archive/production.zip" -O get5.zip
RUN unzip get5.zip
RUN mv get5-web-production get5-web
WORKDIR get5-web
RUN pip install -r requirements.txt
ADD entry.sh entry.sh
RUN chmod a+rx entry.sh
ADD prod_config.py instance/prod_config.py

CMD ./entry.sh
